### ISSUE TITLE
Question about a change

### ISSUE THREAD

**Issue by the-r3dacted** [Mibo5354/i9300_builds#5]
I don't own a i9300, I might in the future, but that means I don't know if this is just a problem it has. I'm curious why you "Forced disable Bluetooth absolute volume"?

**Comment by Mibo5354** [comment]
The toggle for the option in developer settings didn't work properly and I wanted it turned on for my own use. I couldn't be bothered to fix the actual issue.
By the way this is the change I made: https://github.com/Mibo5354/android_packages_apps_Bluetooth/commit/966825d153a059776e4f256999ce437fcdb939e9
You could revert this commit and backport this [patch](https://review.lineageos.org/c/LineageOS/android_system_bt/+/233608) from the lineage-16.0 branch if you wanted to possibly fix it.

**Comment by the-r3dacted** [comment]
Ok, but why me? I don't really care since I like a wire myself, I just found it curious enough to ask.

**Comment by Mibo5354** [comment]
If it's turned on, the volume would be too loud even if it's on the lowest volume. I have the same problem with wired headphones, hence I've turned it down in the default settings too. That's why there's someone complaining that the volume is too low in another issue.
________________________________
